# Generated by Django 3.2.7 on 2021-10-13 16:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_diarista_cep'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='diarista',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
