# Generated by Django 3.2.8 on 2021-10-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_diarista_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='diarista',
            name='foto_usuario',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
